###################################################
# This creates and stands up the development
# docker container. Depends on the Dockerfile and
# docker-start.sh files.
###################################################

# services:
#   actual-development:
#     build: .
#     image: actual-development
#     environment:
#       - HTTPS
#     ports:
#       - '3001:3001'
#     volumes:
#       - '.:/app'
#     restart: 'no'

version: '3.8'

services:
  actual:
    image: actualbudget/actual-server:latest
    container_name: actual
    ports:
      - "5006:5006"
    volumes:
      - actual_data:/data
    environment:
      - ACTUAL_ENV=production
      - ACTUAL_UPLOAD_FILE=true
      - ACTUAL_URL=https://budget.yesvara.com
    labels:
      - coolify.network.port=5006  # Only this
    restart: unless-stopped

volumes:
  actual_data:
